/* eslint-disable prettier/prettier */
export const premierLeagueTeams = [
    {
        name: "Manchester United",
        location: "Manchester",
        stadium: "Old Trafford",
        manager: "Erik ten Hag",
        rank: 1,
    },
    {
        name: "Manchester City",
        location: "Manchester",
        stadium: "Etihad Stadium",
        manager: "Pep Guardiola",
        rank: 2,
    },
    {
        name: "Liverpool",
        location: "Liverpool",
        stadium: "Anfield",
        manager: "Jürgen Klopp",
        rank: 3,
    },
    {
        name: "Arsenal",
        location: "London",
        stadium: "Emirates Stadium",
        manager: "Mikel Arteta",
        rank: 4,
    },
    {
        name: "Chelsea",
        location: "London",
        stadium: "Stamford Bridge",
        manager: "Mauricio Pochettino",
        rank: 5,
    },
    {
        name: "Tottenham Hotspur",
        location: "London",
        stadium: "Tottenham Hotspur Stadium",
        manager: "Ange Postecoglou",
        rank: 6,
    },
    {
        name: "Newcastle United",
        location: "Newcastle upon Tyne",
        stadium: "St James' Park",
        manager: "Eddie Howe",
        rank: 7,
    },
    {
        name: "Aston Villa",
        location: "Birmingham",
        stadium: "Villa Park",
        manager: "Unai Emery",
        rank: 8,
    },
    {
        name: "Brighton & Hove Albion",
        location: "Brighton",
        stadium: "Falmer Stadium",
        manager: "Roberto De Zerbi",
        rank: 9,
    },
    {
        name: "West Ham United",
        location: "London",
        stadium: "London Stadium",
        manager: "David Moyes",
        rank: 10,
    },
    {
        name: "Brentford",
        location: "London",
        stadium: "Gtech Community Stadium",
        manager: "Thomas Frank",
        rank: 11,
    },
    {
        name: "Fulham",
        location: "London",
        stadium: "Craven Cottage",
        manager: "Marco Silva",
        rank: 12,
    },
    {
        name: "Crystal Palace",
        location: "London",
        stadium: "Selhurst Park",
        manager: "Oliver Glasner",
        rank: 13,
    },
    {
        name: "Wolverhampton Wanderers",
        location: "Wolverhampton",
        stadium: "Molineux Stadium",
        manager: "Gary O'Neil",
        rank: 14,
    },
    {
        name: "Nottingham Forest",
        location: "Nottingham",
        stadium: "City Ground",
        manager: "Nuno Espírito Santo",
        rank: 15,
    },
    {
        name: "Everton",
        location: "Liverpool",
        stadium: "Goodison Park",
        manager: "Sean Dyche",
        rank: 16,
    },
    {
        name: "AFC Bournemouth",
        location: "Bournemouth",
        stadium: "Vitality Stadium",
        manager: "Andoni Iraola",
        rank: 17,
    },
    {
        name: "Leicester City",
        location: "Leicester",
        stadium: "King Power Stadium",
        manager: "Enzo Maresca",
        rank: 18,
    },
    {
        name: "Southampton",
        location: "Southampton",
        stadium: "St Mary's Stadium",
        manager: "Russell Martin",
        rank: 19,
    },
    {
        name: "Leeds United",
        location: "Leeds",
        stadium: "Elland Road",
        manager: "Daniel Farke",
        rank: 20,
    },
];
